### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by ghost** [NusantaraProject-ROM/android_packages_apps_Launcher3#1]
packages/apps/Launcher3/src/com/android/launcher3/icons/ThirdPartyIconProvider.java:12: error: cannot find symbol
import static com.android.launcher3.icons.BaseIconFactory.CONFIG_HINT_NO_WRAP;
^
  symbol:   static CONFIG_HINT_NO_WRAP
  location: class BaseIconFactory
packages/apps/Launcher3/src/com/android/launcher3/icons/pack/IconResolverMasked.java:19: error: cannot find symbol
import static com.android.launcher3.icons.LauncherIcons.CONFIG_HINT_NO_WRAP;
^
  symbol:   static CONFIG_HINT_NO_WRAP
  location: class LauncherIcons
packages/apps/Launcher3/src/com/android/launcher3/icons/ThirdPartyIconProvider.java:36: error: cannot find symbol
        icon.setChangingConfigurations(icon.getChangingConfigurations() | CONFIG_HINT_NO_WRAP);
                                                                          ^
  symbol:   variable CONFIG_HINT_NO_WRAP
  location: class ThirdPartyIconProvider
3 errors
02:25:15 ninja failed with: exit status 1

Revert Commit not possible (Conflicts)

**Comment by goodmeow** [comment]
resync, iconlib was added
